baseURL = 'https://partiallytyped.github.io'
languageCode = 'en-us'
title = 'PartiallyTyped'

theme="hugo-xmin"
copyright = "© PartiallyTyped"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4